<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-11T16:28:25 IST" name="Suite" finished-at="2024-09-11T16:28:34 IST" duration-ms="9423">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:features.TestRunner@45b4c3a9]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2024-09-11T16:28:25 IST" name="Test" finished-at="2024-09-11T16:28:34 IST" duration-ms="9423">
      <class name="features.TestRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:features.TestRunner@45b4c3a9]" started-at="2024-09-11T16:28:25 IST" name="setUpClass" finished-at="2024-09-11T16:28:25 IST" duration-ms="387" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@f1266c6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:features.TestRunner@45b4c3a9]" started-at="2024-09-11T16:28:25 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-09-11T16:28:33 IST" duration-ms="8401" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify successful login"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login functionality"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Could not login expected [https://freshers.dspf-dev.com/mypage/profile/] but found [https://freshers.dspf-dev.com/login/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Could not login expected [https://freshers.dspf-dev.com/mypage/profile/] but found [https://freshers.dspf-dev.com/login/]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at stepDefinitions.LoginSteps.i_redirect_to_profile_page(LoginSteps.java:87)
at âœ½.I redirect to profile page(file:///C:/Users/prasa/eclipse-workspace/YaaayFreshers/src/test/java/features/Login.feature:31)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:features.TestRunner@45b4c3a9]" started-at="2024-09-11T16:28:33 IST" name="tearDownClass" finished-at="2024-09-11T16:28:34 IST" duration-ms="596" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- features.TestRunner -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
