<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="5" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-12T14:20:28 IST" name="Suite" finished-at="2024-11-12T14:21:09 IST" duration-ms="41153">
    <groups>
    </groups>
    <test started-at="2024-11-12T14:20:28 IST" name="Test" finished-at="2024-11-12T14:21:09 IST" duration-ms="41153">
      <class name="com.zenken.freshers.user.FieldOfStudy">
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.zenken.freshers.user.FieldOfStudy@51bf5add]" started-at="2024-11-12T14:20:28 IST" name="setup" finished-at="2024-11-12T14:20:30 IST" duration-ms="1853" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.zenken.freshers.user.FieldOfStudy.verifyITOptionSelection()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="setUpTest()[pri:0, instance:com.zenken.freshers.user.FieldOfStudy@51bf5add]" started-at="2024-11-12T14:20:30 IST" name="setUpTest" finished-at="2024-11-12T14:20:38 IST" duration-ms="7939" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method retried="true" signature="verifyITOptionSelection()[pri:0, instance:com.zenken.freshers.user.FieldOfStudy@51bf5add]" started-at="2024-11-12T14:20:38 IST" name="verifyITOptionSelection" description="This test verifies that an IT option can be saved and is displayed accordingly on preview page" finished-at="2024-11-12T14:20:41 IST" duration-ms="3548" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Area of research is incorrect expected [ITa] but found [IT]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Area of research is incorrect expected [ITa] but found [IT]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.zenken.freshers.user.FieldOfStudy.verifyITOptionSelection(FieldOfStudy.java:177)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyITOptionSelection -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.zenken.freshers.user.FieldOfStudy@51bf5add]" started-at="2024-11-12T14:20:41 IST" name="tearDown" finished-at="2024-11-12T14:20:41 IST" duration-ms="180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.zenken.freshers.user.FieldOfStudy@51bf5add]" started-at="2024-11-12T14:20:41 IST" name="setup" finished-at="2024-11-12T14:20:42 IST" duration-ms="776" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.zenken.freshers.user.FieldOfStudy.verifyITOptionSelection()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="setUpTest()[pri:0, instance:com.zenken.freshers.user.FieldOfStudy@51bf5add]" started-at="2024-11-12T14:20:42 IST" name="setUpTest" finished-at="2024-11-12T14:20:51 IST" duration-ms="8668" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method retried="true" signature="verifyITOptionSelection()[pri:0, instance:com.zenken.freshers.user.FieldOfStudy@51bf5add]" started-at="2024-11-12T14:20:51 IST" name="verifyITOptionSelection" description="This test verifies that an IT option can be saved and is displayed accordingly on preview page" finished-at="2024-11-12T14:20:54 IST" duration-ms="3176" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Area of research is incorrect expected [ITa] but found [IT]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Area of research is incorrect expected [ITa] but found [IT]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.zenken.freshers.user.FieldOfStudy.verifyITOptionSelection(FieldOfStudy.java:177)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyITOptionSelection -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.zenken.freshers.user.FieldOfStudy@51bf5add]" started-at="2024-11-12T14:20:54 IST" name="tearDown" finished-at="2024-11-12T14:20:54 IST" duration-ms="157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.zenken.freshers.user.FieldOfStudy@51bf5add]" started-at="2024-11-12T14:20:54 IST" name="setup" finished-at="2024-11-12T14:20:55 IST" duration-ms="779" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.zenken.freshers.user.FieldOfStudy.verifyITOptionSelection()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="setUpTest()[pri:0, instance:com.zenken.freshers.user.FieldOfStudy@51bf5add]" started-at="2024-11-12T14:20:55 IST" name="setUpTest" finished-at="2024-11-12T14:21:04 IST" duration-ms="9558" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method signature="verifyITOptionSelection()[pri:0, instance:com.zenken.freshers.user.FieldOfStudy@51bf5add]" started-at="2024-11-12T14:21:04 IST" name="verifyITOptionSelection" description="This test verifies that an IT option can be saved and is displayed accordingly on preview page" finished-at="2024-11-12T14:21:08 IST" duration-ms="3697" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Area of research is incorrect expected [ITa] but found [IT]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Area of research is incorrect expected [ITa] but found [IT]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.zenken.freshers.user.FieldOfStudy.verifyITOptionSelection(FieldOfStudy.java:177)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyITOptionSelection -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.zenken.freshers.user.FieldOfStudy@51bf5add]" started-at="2024-11-12T14:21:09 IST" name="tearDown" finished-at="2024-11-12T14:21:09 IST" duration-ms="141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.zenken.freshers.user.FieldOfStudy -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
